<?php
namespace Heyday\Component\Beam\DeploymentProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-15 at 11:01:03.
 */
class DeploymentResultTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DeploymentResult
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new DeploymentResult;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    public function testConstruct()
    {

    }
}
