<?php
namespace Heyday\Component\Beam\Deployment;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-07 at 12:04:41.
 */
class RsyncTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Rsync
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Rsync;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\Component\Beam\Deployment\Rsync::setBeam
     * @todo   Implement testSetBeam().
     */
    public function testSetBeam()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Deployment\Rsync::deploy
     * @todo   Implement testDeploy().
     */
    public function testDeploy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Deployment\Rsync::getRemotePath
     * @todo   Implement testGetRemotePath().
     */
    public function testGetRemotePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
