<?php
namespace Heyday\Component\Beam\Vcs;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-07 at 12:04:41.
 */
class GitTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Git
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Git;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\Component\Beam\Vcs\Git::getCurrentBranch
     * @todo   Implement testGetCurrentBranch().
     */
    public function testGetCurrentBranch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Vcs\Git::getAvailableBranches
     * @todo   Implement testGetAvailableBranches().
     */
    public function testGetAvailableBranches()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Vcs\Git::exists
     * @todo   Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Vcs\Git::exportBranch
     * @todo   Implement testExportBranch().
     */
    public function testExportBranch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Vcs\Git::updateBranch
     * @todo   Implement testUpdateBranch().
     */
    public function testUpdateBranch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
