<?php
namespace Heyday\Component\Beam;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-07 at 12:04:41.
 */
class ApplicationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Application
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Application;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\Component\Beam\Application::getDefinition
     * @todo   Implement testGetDefinition().
     */
    public function testGetDefinition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
