<?php
namespace Heyday\Component\Beam\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-15 at 11:01:02.
 */
class RsyncCommandTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RsyncCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RsyncCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    public function testRun()
    {
        $this->markTestIncomplete();
    }
}
