<?php
namespace Heyday\Component\Beam\Config;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-07 at 12:04:41.
 */
class JsonConfigLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var JsonConfigLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new JsonConfigLoader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\Component\Beam\Config\JsonConfigLoader::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Config\JsonConfigLoader::locate
     * @todo   Implement testLocate().
     */
    public function testLocate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Config\JsonConfigLoader::supports
     * @todo   Implement testSupports().
     */
    public function testSupports()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
