<?php
namespace Heyday\Component\Beam\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-07 at 12:04:41.
 */
class ChangesHelperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ChangesHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new ChangesHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\Component\Beam\Helper\ChangesHelper::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Helper\ChangesHelper::outputChanges
     * @todo   Implement testOutputChanges().
     */
    public function testOutputChanges()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Component\Beam\Helper\ChangesHelper::outputChangesSummary
     * @todo   Implement testOutputChangesSummary().
     */
    public function testOutputChangesSummary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
