<?php
namespace Heyday\Beam\DeploymentProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-15 at 11:01:03.
 */
class DeploymentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Deployment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new Deployment;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\Beam\DeploymentProvider\Deployment::setBeam
     * @todo   Implement testSetBeam().
     */
    public function testSetBeam()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
