<?php
namespace Heyday\Beam\DeploymentProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-15 at 11:01:03.
 */
class SftpTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Sftp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Sftp;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Heyday\Beam\DeploymentProvider\Sftp::up
     * @todo   Implement testUp().
     */
    public function testUp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Beam\DeploymentProvider\Sftp::down
     * @todo   Implement testDown().
     */
    public function testDown()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Beam\DeploymentProvider\Sftp::getTargetPath
     * @todo   Implement testGetTargetPath().
     */
    public function testGetTargetPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Heyday\Beam\DeploymentProvider\Sftp::getLimitations
     * @todo   Implement testGetLimitations().
     */
    public function testGetLimitations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
